import scores from "./data/scores.json";

// Standalone "Model Scores" panel: NER F1, linking accuracy, and the
// disambiguation scoring-technique comparison (multiple embedding models x
// multiple scoring formulas, see scripts/compare_scoring_techniques.py),
// each broken out by language. Data is generated by the eval scripts under
// scripts/ and src/mel/eval/, not hand-typed into the UI.
export default function ScoresPanel({ onClose }) {
  const best = [...scores.scoring_comparison.rows].sort((a, b) => b.accuracy - a.accuracy)[0];

  return (
    <div className="scores-overlay" onClick={onClose}>
      <div className="scores-panel fade-in" onClick={(e) => e.stopPropagation()}>
        <div className="details-header">
          <h2>Model &amp; Scoring Evaluation</h2>
          <button className="text-btn" onClick={onClose}>
            Close
          </button>
        </div>

        <section className="scores-section">
          <h3>NER (fine-tuned model, WikiAnn test set)</h3>
          <p className="muted small">{scores.ner.note}</p>
          <div className="score-table-wrap">
            <table className="score-table">
              <thead>
                <tr>
                  <th>Language</th>
                  <th>Precision</th>
                  <th>Recall</th>
                  <th>F1</th>
                </tr>
              </thead>
              <tbody>
                {scores.ner.rows.map((r) => (
                  <tr key={r.lang}>
                    <td>{r.language}</td>
                    <td>{r.precision != null ? r.precision.toFixed(3) : "\u2014"}</td>
                    <td>{r.recall != null ? r.recall.toFixed(3) : "\u2014"}</td>
                    <td>{r.f1.toFixed(3)}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
          <p className="muted small">Combined test-set F1: {scores.ner.combined_f1.toFixed(3)}</p>
        </section>

        <section className="scores-section">
          <h3>NER (deployed model, live evaluation)</h3>
          <p className="muted small">{scores.ner_deployed_model.note}</p>
          <div className="score-table-wrap">
            <table className="score-table">
              <thead>
                <tr>
                  <th>Language</th>
                  <th>PER F1</th>
                  <th>ORG F1</th>
                  <th>LOC F1</th>
                  <th>Macro F1</th>
                </tr>
              </thead>
              <tbody>
                {scores.ner_deployed_model.rows.map((r) => (
                  <tr key={r.lang}>
                    <td>{r.language}</td>
                    <td>{r.per_f1.toFixed(3)}</td>
                    <td>{r.org_f1.toFixed(3)}</td>
                    <td>{r.loc_f1.toFixed(3)}</td>
                    <td>{r.macro_f1.toFixed(3)}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
          <p className="muted small">
            Combined macro F1: {scores.ner_deployed_model.combined_macro_f1.toFixed(3)}. ORG recall lags PER/LOC in
            every language — likely an entity-boundary/label-scheme mismatch between this model's ORG convention and
            WikiAnn's, not a random error.
          </p>
          <div className="eval-figures">
            <img src={scores.ner_deployed_model.training_curve_image} alt="NER training curve" />
            <img src={scores.ner_deployed_model.images.combined} alt="Combined confusion matrix" />
          </div>
        </section>

        <section className="scores-section">
          <h3>Entity linking accuracy (hand-authored gold set)</h3>
          <p className="muted small">{scores.linking.note}</p>
          <div className="score-table-wrap">
            <table className="score-table">
              <thead>
                <tr>
                  <th>Language</th>
                  <th>Accuracy</th>
                  <th>Correct / Total</th>
                </tr>
              </thead>
              <tbody>
                {scores.linking.rows.map((r) => (
                  <tr key={r.lang}>
                    <td>{r.language}</td>
                    <td>{(r.accuracy * 100).toFixed(1)}%</td>
                    <td>
                      {r.correct}/{r.total}
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
          <p className="muted small">
            Overall: {(scores.linking.overall_accuracy * 100).toFixed(1)}% ({scores.linking.overall_n} examples)
          </p>
        </section>

        <section className="scores-section">
          <h3>Scoring technique comparison</h3>
          <p className="muted small">{scores.scoring_comparison.note}</p>
          {scores.scoring_comparison.rows.length === 0 ? (
            <p className="muted">
              Not generated yet — run <code>python scripts/compare_scoring_techniques.py</code>.
            </p>
          ) : (
            <>
              <div className="score-table-wrap">
                <table className="score-table">
                  <thead>
                    <tr>
                      <th>Embedding model</th>
                      <th>Scoring method</th>
                      <th>Accuracy</th>
                      <th>EN</th>
                      <th>HI</th>
                      <th>ES</th>
                      <th>DE</th>
                    </tr>
                  </thead>
                  <tbody>
                    {scores.scoring_comparison.rows.map((r, i) => (
                      <tr key={i} className={best && r === best ? "score-row-winner" : ""}>
                        <td>{r.embedding_model}</td>
                        <td>{r.method}</td>
                        <td>{(r.accuracy * 100).toFixed(1)}%</td>
                        <td>{r.acc_en != null ? (r.acc_en * 100).toFixed(0) + "%" : "\u2014"}</td>
                        <td>{r.acc_hi != null ? (r.acc_hi * 100).toFixed(0) + "%" : "\u2014"}</td>
                        <td>{r.acc_es != null ? (r.acc_es * 100).toFixed(0) + "%" : "\u2014"}</td>
                        <td>{r.acc_de != null ? (r.acc_de * 100).toFixed(0) + "%" : "\u2014"}</td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
              {best && (
                <p className="muted small">
                  Best combination: <strong>{best.embedding_model}</strong> + <strong>{best.method}</strong> (
                  {(best.accuracy * 100).toFixed(1)}%)
                </p>
              )}
            </>
          )}
        </section>
      </div>
    </div>
  );
}
